### ISSUE TITLE
您好，方便添加一个新的superWebView。 

### ISSUE THREAD

**Issue by songhongkang** [MakeItEasy/MWApiCloud-SuperWebview-Demo#1]
pod成功了。。加载一些过一会会奔溃。

**Comment by MakeItEasy** [comment]
@songhongkang 这个是一个比较过时的iOS工程了（3年前），所以如果你使用有问题的话，先搞清楚崩溃的原因，是不是iOS操作系统的升级，可能之前的一些工程的配置导致的。一句话，确实看不出来是什么原因。

另外，也关注一下ApiCloud本身的版本是否也可能升级了，毕竟这个Demo项目引用的pod（https://github.com/makeiteasy/MWApiCloud-SuperWebview）也是个3年前的项目了。

希望以上对你解决问题有帮助。

**Comment by songhongkang** [comment]
谢谢！已经解决了。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 代如刚 <notifications@github.com&gt;
发送时间: 2020年2月21日 23:25
收件人: MakeItEasy/MWApiCloud-SuperWebview-Demo <MWApiCloud-SuperWebview-Demo@noreply.github.com&gt;
抄送: songhongkang <139994824@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[MakeItEasy/MWApiCloud-SuperWebview-Demo] 您好，方便添加一个新的superWebView。  (#1)
